# Generated by Django 4.2.6 on 2024-02-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtranslation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
