# Generated by Django 4.2.6 on 2024-01-16 13:59

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MotorcycleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification',
                                      to='motor.motorcycle')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MotorcycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('image', models.FileField(upload_to='motorcycle/more_images/')),
                ('generated_image_number', models.PositiveIntegerField(default=0, editable=False)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                                 to='motor.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('deposit', models.PositiveIntegerField(verbose_name='Motorcycle deposit price')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit',
                                                    to='motor.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Motorcycle name')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, default='Motorcycle', editable=False, max_length=11)),
                ('price_1_to_7_days', models.PositiveIntegerField(verbose_name='Price 1 to 7 days rent')),
                ('price_8_to_14_days', models.PositiveIntegerField(verbose_name='Price 8 to 14 days rent')),
                ('price_15_to_21_days', models.PositiveIntegerField(verbose_name='Price 15 to 21 days rent')),
                ('price_22_to_30_days', models.PositiveIntegerField(verbose_name='Price 22 to 30 days rent')),
                ('main_image',
                 models.FileField(upload_to='motorcycle/main_images/', verbose_name='Motorcycle main image')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                                on_delete=django.db.models.deletion.CASCADE,
                                                                related_name='translations', to='motor.motorcycle')),
            ],
            options={
                'verbose_name': 'motorcycle Translation',
                'db_table': 'motor_motorcycle_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MotorcycleSpecificationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('specifications', models.CharField(max_length=255, verbose_name='Motorcycle specifications')),
                ('save_control', models.CharField(max_length=255, verbose_name='Motorcycle save control')),
                ('suspensions', models.CharField(max_length=255, verbose_name='Motorcycle suspensions')),
                ('clutch', models.CharField(max_length=255, verbose_name='Motorcycle clutch')),
                ('brakes', models.CharField(max_length=255, verbose_name='Motorcycle brakes')),
                ('weight', models.CharField(max_length=255, verbose_name='Motorcycle weight')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                                on_delete=django.db.models.deletion.CASCADE,
                                                                related_name='translations',
                                                                to='motor.motorcyclespecification')),
            ],
            options={
                'verbose_name': 'motorcycle specification Translation',
                'db_table': 'motor_motorcyclespecification_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
