# Generated by Django 4.2.6 on 2024-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
