# Generated by Django 4.2.6 on 2024-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rental_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
