# Generated by Django 4.2.6 on 2024-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_contactus_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
